"""napravljena tablica kolegiji

Revision ID: 05a9b5f6e1bc
Revises: 84cc61fdbff7
Create Date: 2026-03-26 16:50:58.202232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a9b5f6e1bc'
down_revision = '84cc61fdbff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kolegiji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=60), nullable=False),
    sa.Column('ects', sa.Integer(), nullable=False),
    sa.Column('semestar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kolegiji')
    # ### end Alembic commands ###
