"""Povezan Profesor i Kolegij

Revision ID: 106dfae448cf
Revises: 05a9b5f6e1bc
Create Date: 2026-03-26 16:55:51.755720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106dfae448cf'
down_revision = '05a9b5f6e1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kolegiji', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nositelj_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profesori', ['nositelj_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kolegiji', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nositelj_id')

    # ### end Alembic commands ###
