"""napravljena tablica profesori

Revision ID: 84cc61fdbff7
Revises: 
Create Date: 2026-03-26 16:46:37.448591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cc61fdbff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=30), nullable=False),
    sa.Column('prezime', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('titula', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesori')
    # ### end Alembic commands ###
